assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: GI01SUMO-RII11-02-PCO2WC053
stream:
  method: recovered_inst
  name: pco2w_abc_metadata
workflow_config:
  schedule: 0 0 * * *
